#!/bin/bash
set -e

ls -l

CMD=../bin/rancher
if [ ! -x $CMD ]; then
    echo Running: build-server
    $(dirname $0)/build-server
else
  echo "Doing somethings: ${CATTLE_KDM_BRANCH}"

  ## this is from `scripts/build-server`
  source $(dirname $0)/version
  source $(dirname $0)/export-config

  cd $(dirname $0)/..

  mkdir -p bin
  if  [ -n "$CATTLE_KDM_BRANCH" ]; then
      echo "Here: $(pwd)"
      curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${CATTLE_KDM_BRANCH}/data.json > bin/data.json
  elif [ ! -e bin/data.json ] && [ -e ../kontainer-driver-metadata/data/data.json ]; then
      echo "Here 2: $(pwd)"
      cp ../kontainer-driver-metadata/data/data.json bin/data.json
  else
      echo "Not Reached: $(pwd)"
  fi

  cd scripts

  echo "Another ting: $(pwd)"
fi


echo Running: build-agent
$(dirname $0)/build-agent
