#!/bin/bash
set -e

echo "CATTLE_KDM_BRANCH is set to: $CATTLE_KDM_BRANCH"

mkdir -p bin dist
if [ -e ./scripts/$1 ]; then
    ./scripts/"$@"
else
    exec "$@"
fi

chown -R $DAPPER_UID:$DAPPER_GID .
