#!/bin/bash
set -e

echo Starting rancher server

source $(dirname $0)/version
source $(dirname $0)/export-config
cd scripts
source ./package-env
cd ..

cd $(dirname $0)/..

if [ ! -z $1 ] && ( [ $1 = "--trace" ] || [ $1 = "--info" ] || [ $1 = "--debug" ] ); then
  LOGFLAG=$1
fi

rm -rf build/testdata
mkdir -p build/testdata
cd build/testdata
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export CATTLE_DEV_MODE=yes
export CATTLE_SERVER_URL="https://$(ip route get 8.8.8.8 | awk '{print $7}'):8443"
export CATTLE_BOOTSTRAP_PASSWORD="admin"
export CATTLE_FEATURES="harvester=false"

cat << EOF 
docker run -d --name rancher-server \
  --restart=unless-stopped --privileged \
  -p 443:443 -p 6443:6443 -p 8080:8080 \
  -e CATTLE_BOOTSTRAP_PASSWORD=$CATTLE_BOOTSTRAP_PASSWORD \
  $IMAGE
EOF

docker run -d --name rancher-server \
  --restart=unless-stopped --privileged \
  -p 443:443 -p 6443:6443 -p 8080:8080 \
  -e CATTLE_BOOTSTRAP_PASSWORD=$CATTLE_BOOTSTRAP_PASSWORD \
  $IMAGE

sleep 5

mkdir -p /etc/rancher/k3s/
docker cp rancher-server:/etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/k3s.yaml
