name: Running Test Script
on:
  workflow_dispatch:

env:
  K3S_VERSION: v1.30.1+k3s1

jobs:
  #build-server:
    #name: Build rancher server
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout code
        #uses: actions/checkout@v4

      #- name: Set Up Go
        #uses: actions/setup-go@v5
        #with:
          #go-version: '1.21'

      #- name: Install Dependencies
        #run: |
          #sudo apt-get update
          #sudo apt-get install -y jq curl
        #shell: bash

      #- name: Run Build Server
        #run: |
          #./scripts/build-server
        #shell: bash

      #- name: Upload Rancher Binary
        #uses: actions/upload-artifact@v4
        #with:
          #name: rancher
          #path: bin/rancher

  integration-testing:
    name: Integration tests
    runs-on: ubuntu-latest
    #needs:
      #- build-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Rancher Binary
        uses: actions/download-artifact@v4
        with:
          name: rancher
          path: bin
          run-id: 9410755745
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Rancher Binary Executable
        run: chmod +x ./bin/rancher
        shell: bash

      - name: Download and Install k3s
        run: |
          curl -L -o k3s "https://github.com/k3s-io/k3s/releases/download/${{ env.K3S_VERSION }}/k3s"
          chmod +x k3s
          sudo mv k3s /usr/local/bin/
        shell: bash

      - name: Verify k3s Installation
        run: |
          k3s --version
        shell: bash

      - name: Stop Previous k3s Instances
        run: |
          sudo systemctl stop k3s || true
          sudo killall k3s || true
          sudo rm -rf /var/lib/rancher/k3s
          sudo rm -rf /var/lib/kubelet
        shell: bash

      - name: Run Integration Tests
        run: |
          sudo ./scripts/test || (
            cat /tmp/rancher.log &&
            echo "Checking k3s logs..." &&
            (sudo cat /var/log/k3s.log || sudo cat /var/lib/rancher/k3s/server/logs/k3s.log || echo "k3s logs not found") &&
            false
          )
        shell: bash
        env:
          ARCH: amd64
          CI: true
          AGENT_TAG: latest
          CATTLE_SYSTEM_AGENT_VERSION: v0.3.6

      - name: Upload Rancher Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rancher-logs
          path: /tmp/rancher.log
