name: Build PR (Windows Server 2019)
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master 
      - release/v*

jobs:
  build-pr:
    name: Build for Windows Server 2019
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo Docker version
        run: docker.exe --version

      - name: Install Dapper
        run: |
          Invoke-WebRequest -Uri "https://github.com/rancher/dapper/releases/download/v0.6.0/dapper-Windows-x86_64.exe" -OutFile "C:\ProgramData\dapper.exe"
        shell: pwsh

      - name: Set Dapper Path
        run: echo "DAPPER_PATH=C:\ProgramData\dapper.exe" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Verify Dapper installation
        run: $env:DAPPER_PATH --version
        shell: pwsh

      - name: Run Build
        run: dapper.exe -f Dockerfile-windows.dapper -d ci
        env:
          DOCKER_HOST: npipe:////./pipe/docker_engine
