name: Windows Server 2022
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master 
      - release/v*
  push:
    branches:
      - "master"
      - "release/v*"
    tags:
      - "v*"

jobs:
  build-pr:
    if: github.event_name == 'pull_request'
    name: Build Pull Request
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dapper
        run: |
          Invoke-WebRequest -Uri "https://github.com/rancher/dapper/releases/download/v0.6.0/dapper-Windows-x86_64.exe" -OutFile "C:\ProgramData\dapper.exe"
          echo "DAPPER_PATH=C:\ProgramData\dapper.exe" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Verify Dapper installation
        run: |
          Invoke-Expression "$env:DAPPER_PATH --version"
        shell: pwsh

      - name: Run Build
        run: |
          Invoke-Expression "$env:DAPPER_PATH -f Dockerfile-windows.dapper -d ci"
        shell: pwsh

  build-push-tag:
    if: github.event_name == 'push' || github.event_name == 'tag' 
    name: Build Pushed Tag
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dapper
        run: |
          Invoke-WebRequest -Uri "https://github.com/rancher/dapper/releases/download/v0.6.0/dapper-Windows-x86_64.exe" -OutFile "C:\ProgramData\dapper.exe"
          echo "DAPPER_PATH=C:\ProgramData\dapper.exe" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Verify Dapper installation
        run: |
          Invoke-Expression "$env:DAPPER_PATH --version"
        shell: pwsh

      - name: Run Build
        run: |
          Invoke-Expression "$env:DAPPER_PATH -f Dockerfile-windows.dapper -d ci"
        shell: pwsh

      - name: Stage binaries
        run: |
          Copy-Item -Path .\bin\* -Destination .\package\windows\ -Recurse -Force
        shell: pwsh
        env:
          DOCKER_HOST: npipe:////./pipe/docker_engine

  docker-publish:
    if: github.event_name == 'push' || github.event_name == 'tag' 
    name: Publish Pushed Tag
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.STAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.STAGE_REGISTRY_PASSWORD }}

      - name: Build agent.exe
        run: |
          pwsh -File scripts/windows/build-agent.ps1
          Copy-Item -Path .\bin\* -Destination . -Recurse -Force
          Copy-Item -Path .\scripts\windows\* -Destination . -Recurse -Force
        shell: pwsh

      - name: Build and Push Docker Image - Head Agent
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          docker build --build-arg SERVERCORE_VERSION=ltsc2022 --build-arg ARCH=amd64 --build-arg VERSION=${{ github.ref_name }}-${{ github.sha }}-head -f package/windows/Dockerfile.agent -t ${{ secrets.STAGE_REGISTRY_USERNAME }}/rancher:head-agent-${{ github.sha }}-windows-2022 .
          docker push ${{ secrets.STAGE_REGISTRY_USERNAME }}/rancher:head-agent-${{ github.sha }}-windows-2022
        shell: bash

      - name: Build and Push Docker Image - Tag Agent
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker build --build-arg SERVERCORE_VERSION=ltsc2022 --build-arg ARCH=amd64 --build-arg VERSION=${{ github.ref_name }}-${{ github.sha }}-head -f package/windows/Dockerfile.agent -t ${{ secrets.STAGE_REGISTRY_USERNAME }}/rancher:agent-windows-2022 .
          docker push ${{ secrets.STAGE_REGISTRY_USERNAME }}/rancher:agent-windows-2022
        shell: bash
