name: Build PR (Windows Server 2019)
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master 
      - release/v*

jobs:
  build-pr:
    name: Build for Windows Server 2019
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dapper
        run: |
          Invoke-WebRequest -Uri "https://github.com/rancher/dapper/releases/download/v0.6.0/dapper-windows-386.exe" -OutFile "dapper.exe"
          Set-ExecutionPolicy Bypass -Scope Process -Force
          ./dapper.exe --version

      - name: Run Build
        run: dapper.exe -f Dockerfile-windows.dapper -d ci
        env:
          DOCKER_HOST: npipe:////./pipe/docker_engine
